###
GET http://localhost:4004/odata/v4/nautical-quotation/xNAUTIxfinalbid


###

POST http://localhost:4004/odata/v4/nautical-quotation/xNAUTIxfinalbid
Content-Type: application/json

{
      "Voyno": "10000004521",
      "Lifnr": "2900000000",
      "Zcode": "A",
      "Biddate": "2024-08-24",
      "Bidtime": "15:05:13",
      "Chrnmin": "4000000009",
      "CodeDesc": "FRIEGHT COST",
      "Value": "",
      "Cvalue": 200000,
      "Cunit": "",
      "Chrqsdate": "2024-08-25",
      "Chrqstime": "13:16:40",
      "Chrqedate": "2024-08-25",
      "Chrqetime": "18:17:00",
      "DoneBy": false,
      "Uname": "PJAIN",
      "Stat": "",
      "Zmode": "AUTO",
      "Zcom": ""
    }